### ISSUE TITLE
prefix or wildcards

### ISSUE THREAD

**Issue by doniks** [wpilibsuite/sphinxext-rediraffe#62]
Is it possible to write a redirect with wildcards or prefixes? 

For example 
* Redirect "/old/path/"
* To "/new/path/index.html"

Which should redirect any of `/old/path/foo.html` and `/old/path/bar.html` 

I couldn't see anything like that in the documentation

**Comment by TheTripleV** [comment]
No, this repo is designed to redirect concrete pages to each other.

**Comment by TheTripleV** [comment]
What if you want to put a new page that would be covered under the wildcard? That would need some kind of ordering or exclusion mechanism.

That's why rediraffe only does page to page redirects.

If you want to redirect lots of pages, I suggest you use the git integration to try and autodetect your redirects or use a scraper to generate a list of all the urls that will be changing

**Comment by doniks** [comment]
Understood. Thanks for the quick clarification
